#![crate_id = "regexp#0.1.0"]
#![crate_type = "rlib"]
#![crate_type = "dylib"]
#![license = "UNLICENSE"]
#![doc(html_root_url = "http://burntsushi.net/rustdoc/regexp")]

//! Regular expressions for Rust.

#![feature(macro_rules, phase)]

extern crate collections;
#[phase(syntax, link)]
extern crate log;
extern crate rand;

#[cfg(bench)]
extern crate stdtest = "test";

use std::fmt;
use std::str;
use parse::is_punct;

pub use parse::Error;
pub use regexp::{Regexp, Captures, SubCaptures, SubCapturesPos};
pub use regexp::{FindCaptures, FindMatches};
pub use regexp::{Replacer, NoExpand, RegexpSplits, RegexpSplitsN};

mod compile;
mod parse;
mod regexp;
mod vm;

#[cfg(test)]
mod test;

impl fmt::Show for Error {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f.buf, "Regexp syntax error near position {}: {}",
               self.pos, self.msg)
    }
}

/// Escapes all regular expression meta characters in `text` so that it may be
/// safely used in a regular expression as a literal string.
pub fn quote(text: &str) -> ~str {
    let mut quoted = str::with_capacity(text.len());
    for c in text.chars() {
        if is_punct(c) {
            quoted.push_char('\\')
        }
        quoted.push_char(c);
    }
    quoted
}

/// Tests if the given regular expression matches somewhere in the text given.
///
/// If there was a problem compiling the regular expression, an error is
/// returned.
pub fn is_match(regex: &str, text: &str) -> Result<bool, Error> {
    Regexp::new(regex).map(|r| r.is_match(text))
}

/// The `program` module exists to support the `re!` macro. Do not use.
#[doc(hidden)]
pub mod program {
    // Exporting this stuff is bad form, but it's necessary for two reasons.
    // Firstly, the `re!` syntax extension is in a different crate and requires
    // access to the representation of a regexp (particularly the instruction
    // set) in order to generate an AST. This could be mitigated if `re!` was
    // defined in the same crate, but this has undesirable consequences (such
    // as requiring dynamic linking to `libsyntax`).
    // Secondly, the AST generated by `re!` must *also* be able to access the
    // representation of a regexp program so that it may be constructed
    // staticly. Yes, this means a user program will actually construct a
    // program using actual instructions, but it's all hidden behind the `re!`
    // macro. This, AFAIK, is impossible to mitigate.
    //
    // For similar reasons, the representation of `Regexp` is also exported
    // but is hidden in the public API documentation.
    //
    // On the bright side, `rustdoc` lets us hide this from the public API
    // documentation, which is an acceptable compromise.
    pub use super::compile::{
        Program, MaybeStatic,
        Inst, OneChar, CharClass, Any, Save, Jump, Split,
        Match, EmptyBegin, EmptyEnd, EmptyWordBoundary,
        Dynamic, Static,
    };
}
